### ISSUE TITLE
pip install nashpy doesn't have requirements.txt

### ISSUE THREAD

**Issue by dudeymopster** [drvinceknight/Nashpy#149]
I do: `pip install nashpy`
This happens:
`Collecting nashpy
  Downloading nashpy-0.0.22.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\12369\.conda\envs\hypergan\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\12369\\AppData\\Local\\Temp\\pip-install-nd6240ob\\nashpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\12369\\AppData\\Local\\Temp\\pip-install-nd6240ob\\nashpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\12369\AppData\Local\Temp\pip-pip-egg-info-g_yz6p3g'
         cwd: C:\Users\12369\AppData\Local\Temp\pip-install-nd6240ob\nashpy\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\12369\AppData\Local\Temp\pip-install-nd6240ob\nashpy\setup.py", line 6, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

I've tried a .whl file,  but I NEED python 3.6 nashpy

**Comment by drvinceknight** [comment]
Hi @dudeymopster, the latest version of nashpy requires py3.8, if that's not compatible with your needs I believe you should be able to install `0.0.22` by running `python -m pip install nashpy==0.0.22`. Let me know if that doesn't work for you.
